const fs = require('fs');

const data = [
  { pali: "pattiṃ", meaning: { en: "acquisition; attainment; merit", pt: "aquisição; realização; mérito", es: "adquisición; logro; mérito" }, grammar: "noun (acc. sing.)" },
  { pali: "pattidānānumodanā", meaning: { en: "rejoicing in the sharing of merit", pt: "regozijo na partilha do mérito", es: "regocijo en el compartir del mérito" }, grammar: "noun" },
  { pali: "pattidānaṃ", meaning: { en: "sharing of merit", pt: "partilha do mérito", es: "compartir del mérito" }, grammar: "noun" },
  { pali: "patti", meaning: { en: "acquisition; attainment; merit", pt: "aquisição; realização; mérito", es: "adquisición; logro; mérito" }, grammar: "noun" },
  { pali: "pasāde", meaning: { en: "clarity; brightness; faith", pt: "clareza; brilho; fé", es: "claridad; brillo; fe" }, grammar: "noun (loc. sing.)" },
  { pali: "pasaṃsā", meaning: { en: "praise", pt: "elogio", es: "elogio" }, grammar: "noun" },
  { pali: "pariyāyatova", meaning: { en: "by way of method; completely", pt: "por meio de método; completamente", es: "por medio de método; completamente" }, grammar: "adverb" },
  { pali: "pariyattibhājanatthato", meaning: { en: "by way of the meaning of sharing the mastery of texts", pt: "pelo significado de partilhar o domínio dos textos", es: "por el significado de compartir el dominio de los textos" }, grammar: "adverb" },
  { pali: "parivattati", meaning: { en: "turns round; rolls", pt: "gira; rola", es: "gira; rueda" }, grammar: "verb" },
  { pali: "parittārammaṇā", meaning: { en: "having a limited object", pt: "tendo um objeto limitado", es: "teniendo un objeto limitado" }, grammar: "adjective" },
  { pali: "parittā", meaning: { en: "limited; small", pt: "limitado; pequeno", es: "limitado; pequeño" }, grammar: "adjective" },
  { pali: "parittesu", meaning: { en: "in limited (things)", pt: "em (coisas) limitadas", es: "en (cosas) limitadas" }, grammar: "adjective (loc. pl.)" },
  { pali: "parittakasubhādīnaṃ", meaning: { en: "of minor beautiful things, etc.", pt: "de coisas belas menores, etc.", es: "de cosas bellas menores, etc." }, grammar: "noun (gen. pl.)" },
  { pali: "parikittito", meaning: { en: "praised; declared", pt: "elogiado; declarado", es: "elogiado; declarado" }, grammar: "adjective (past part.)" },
  { pali: "parikammabhāvanā", meaning: { en: "preliminary development; preliminary meditation", pt: "desenvolvimento preliminar; meditação preliminar", es: "desarrollo preliminar; meditación preliminar" }, grammar: "noun" },
  { pali: "parihīnassa", meaning: { en: "of one who is deprived; of one who has fallen away", pt: "daquele que está privado; daquele que decaiu", es: "de aquel que está privado; de aquel que ha decaído" }, grammar: "adjective (gen. sing.)" },
  { pali: "paridīpitā", meaning: { en: "explained; made clear", pt: "explicado; esclarecido", es: "explicado; aclarado" }, grammar: "adjective (past part.)" },
  { pali: "paridīpitaṃ", meaning: { en: "explained; made clear", pt: "explicado; esclarecido", es: "explicado; aclarado" }, grammar: "adjective (past part.)" },
  { pali: "paribhuñjati", meaning: { en: "enjoys; uses; eats", pt: "desfruta; usa; come", es: "disfruta; usa; come" }, grammar: "verb" },
  { pali: "papañcenti", meaning: { en: "delay; diffuse; multiply", pt: "atrasam; difundem; multiplicam", es: "retrasan; difunden; multiplican" }, grammar: "verb" },
  { pali: "panāyaṃ", meaning: { en: "but this", pt: "mas isto", es: "pero esto" }, grammar: "pronoun" },
  { pali: "panārabbha", meaning: { en: "but beginning with; depending on", pt: "mas começando com; dependendo de", es: "pero comenzando con; dependiendo de" }, grammar: "indeclinable" },
  { pali: "panesā", meaning: { en: "but this", pt: "mas isto", es: "pero esto" }, grammar: "pronoun" },
  { pali: "panaṭṭha", meaning: { en: "but eight", pt: "mas oito", es: "pero ocho" }, grammar: "numeral" },
  { pali: "pakāseyya", meaning: { en: "should explain; should make known", pt: "deveria explicar; deveria tornar conhecido", es: "debería explicar; debería dar a conocer" }, grammar: "verb (optative)" },
  { pali: "pakāseti", meaning: { en: "explains; makes known", pt: "explica; torna conhecido", es: "explica; da a conocer" }, grammar: "verb" },
  { pali: "pakkhipitvā", meaning: { en: "having put in; having added", pt: "tendo colocado; tendo adicionado", es: "habiendo puesto; habiendo añadido" }, grammar: "verb (gerund)" },
  { pali: "pakatiyā", meaning: { en: "by nature", pt: "por natureza", es: "por naturaleza" }, grammar: "noun (inst. sing.)" },
  { pali: "pajahati", meaning: { en: "gives up; abandons", pt: "desiste; abandona", es: "renuncia; abandona" }, grammar: "verb" },
  { pali: "padhānaṃ", meaning: { en: "exertion; effort", pt: "esforço; empenho", es: "esfuerzo; empeño" }, grammar: "noun" },
  { pali: "padesassa", meaning: { en: "of a region; of a portion", pt: "de uma região; de uma porção", es: "de una región; de una porción" }, grammar: "noun (gen. sing.)" },
  { pali: "padaṭṭhānaṃ", meaning: { en: "proximate cause", pt: "causa próxima", es: "causa próxima" }, grammar: "noun" },
  { pali: "paccuppannārammaṇaṃ", meaning: { en: "present object", pt: "objeto presente", es: "objeto presente" }, grammar: "noun" },
  { pali: "paccuppannā", meaning: { en: "present", pt: "presente", es: "presente" }, grammar: "adjective" },
  { pali: "paccupaṭṭhānaṃ", meaning: { en: "manifestation", pt: "manifestação", es: "manifestación" }, grammar: "noun" },
  { pali: "pacchākāle", meaning: { en: "in the subsequent time", pt: "no tempo subsequente", es: "en el tiempo subsecuente" }, grammar: "noun (loc. sing.)" },
  { pali: "pacceti", meaning: { en: "falls back on; realizes", pt: "recorre a; percebe", es: "recurre a; se da cuenta" }, grammar: "verb" },
  { pali: "paccekameva", meaning: { en: "individually; separately", pt: "individualmente; separadamente", es: "individualmente; por separado" }, grammar: "adverb" },
  { pali: "paccayato", meaning: { en: "by way of condition", pt: "por meio de condição", es: "por medio de condición" }, grammar: "adverb" },
  { pali: "paccayabhāvena", meaning: { en: "by being a condition", pt: "por ser uma condição", es: "por ser una condición" }, grammar: "adverb" },
  { pali: "paccavekkhato", meaning: { en: "of one reviewing", pt: "daquele que revisa", es: "del que revisa" }, grammar: "verb (pres. part.)" },
  { pali: "pabhuti", meaning: { en: "beginning with; since", pt: "começando com; desde", es: "comenzando con; desde" }, grammar: "indeclinable" },
  { pali: "nāyaṃ", meaning: { en: "not this", pt: "não isto", es: "no esto" }, grammar: "pronoun" },
  { pali: "nāyako", meaning: { en: "leader", pt: "líder", es: "líder" }, grammar: "noun" },
  { pali: "nānattasaññā", meaning: { en: "perception of diversity", pt: "percepção da diversidade", es: "percepción de la diversidad" }, grammar: "noun" },
  { pali: "nāmarūpānanti", meaning: { en: "mentality-materiality (with quote marker)", pt: "mentalidade-materialidade (com marcador de citação)", es: "mentalidad-materialidad (con marcador de cita)" }, grammar: "noun" },
  { pali: "nāmarūpadhammassa", meaning: { en: "of the mentality-materiality phenomena", pt: "dos fenômenos de mentalidade-materialidade", es: "de los fenómenos de mentalidad-materialidad" }, grammar: "noun (gen. sing.)" },
  { pali: "niṭṭhaṃ", meaning: { en: "conclusion; end", pt: "conclusão; fim", es: "conclusión; fin" }, grammar: "noun" },
  { pali: "niyāmitā", meaning: { en: "fixed; determined", pt: "fixo; determinado", es: "fijo; determinado" }, grammar: "adjective (past part.)" },
  { pali: "niyāmako", meaning: { en: "one who guides; determining factor", pt: "aquele que guia; fator determinante", es: "aquel que guía; factor determinante" }, grammar: "noun" },
  { pali: "niyuttā", meaning: { en: "engaged in; assigned", pt: "engajado em; designado", es: "comprometido en; asignado" }, grammar: "adjective" },
  { pali: "niyatāniyatā", meaning: { en: "fixed and unfixed", pt: "fixo e não fixo", es: "fijo y no fijo" }, grammar: "adjective" },
  { pali: "niyataṃ", meaning: { en: "fixed; sure", pt: "fixo; certo", es: "fijo; seguro" }, grammar: "adjective" },
  { pali: "nissayaṃ", meaning: { en: "support; condition", pt: "suporte; condição", es: "soporte; condición" }, grammar: "noun (acc. sing.)" },
  { pali: "nissayapaccayo", meaning: { en: "support condition", pt: "condição de suporte", es: "condición de soporte" }, grammar: "noun" },
  { pali: "nisinno", meaning: { en: "seated", pt: "sentado", es: "sentado" }, grammar: "adjective (past part.)" },
  { pali: "nirussāhaṃ", meaning: { en: "without effort; without enthusiasm", pt: "sem esforço; sem entusiasmo", es: "sin esfuerzo; sin entusiasmo" }, grammar: "adjective" },
  { pali: "niruddhe", meaning: { en: "when ceased", pt: "quando cessado", es: "cuando cesado" }, grammar: "adjective (loc. sing.)" },
  { pali: "nirodhā", meaning: { en: "from cessation", pt: "da cessação", es: "de la cesación" }, grammar: "noun (abl. sing.)" },
  { pali: "nirodho", meaning: { en: "cessation", pt: "cessação", es: "cesación" }, grammar: "noun" },
  { pali: "niraṅgaṇena", meaning: { en: "free from blemish", pt: "livre de mancha", es: "libre de mancha" }, grammar: "adjective (inst. sing.)" },
  { pali: "nipāto", meaning: { en: "particle (grammar); falling down", pt: "partícula (gramática); queda", es: "partícula (gramática); caída" }, grammar: "noun" },
  { pali: "nipphannā", meaning: { en: "produced; accomplished", pt: "produzido; realizado", es: "producido; realizado" }, grammar: "adjective (past part.)" },
  { pali: "nikanti", meaning: { en: "attachment; desire", pt: "apego; desejo", es: "apego; deseo" }, grammar: "noun" },
  { pali: "nigamanaṃ", meaning: { en: "conclusion", pt: "conclusão", es: "conclusión" }, grammar: "noun" },
  { pali: "niddisitvā", meaning: { en: "having pointed out", pt: "tendo apontado", es: "habiendo señalado" }, grammar: "verb (gerund)" },
  { pali: "nibodhatha", meaning: { en: "understand; learn", pt: "entenda; aprenda", es: "entienda; aprenda" }, grammar: "verb (imperative)" },
  { pali: "nibbānārammaṇattā", meaning: { en: "due to having Nibbāna as object", pt: "devido a ter Nibbana como objeto", es: "debido a tener Nibbana como objeto" }, grammar: "noun (abl. sing.)" },
  { pali: "nibbānassa", meaning: { en: "of Nibbāna", pt: "de Nibbana", es: "de Nibbana" }, grammar: "noun (gen. sing.)" },
  { pali: "nibbattaṃ", meaning: { en: "arisen; produced", pt: "surgido; produzido", es: "surgido; producido" }, grammar: "adjective (past part.)" },
  { pali: "nibbattassa", meaning: { en: "of what has arisen", pt: "daquilo que surgiu", es: "de lo que ha surgido" }, grammar: "adjective (gen. sing.)" },
  { pali: "nevasaññānāsaññāyatanasaññāsahagatanti", meaning: { en: "accompanied by the perception of the base of neither-perception-nor-non-perception", pt: "acompanhado pela percepção da base de nem percepção nem não percepção", es: "acompañado por la percepción de la base de ni percepción ni no percepción" }, grammar: "adjective" },
  { pali: "nayidamevaṃ", meaning: { en: "not this thus", pt: "não isto assim", es: "no esto así" }, grammar: "phrase" },
  { pali: "navamo", meaning: { en: "ninth", pt: "nono", es: "noveno" }, grammar: "numeral" },
  { pali: "mūlaṭṭho", meaning: { en: "fundamental meaning; fundamental state", pt: "significado fundamental; estado fundamental", es: "significado fundamental; estado fundamental" }, grammar: "noun" },
  { pali: "māro", meaning: { en: "Māra", pt: "Mara", es: "Mara" }, grammar: "noun" },
  { pali: "muñcantī", meaning: { en: "releasing", pt: "libertando", es: "liberando" }, grammar: "verb (pres. part.)" },
  { pali: "munivarena", meaning: { en: "by the excellent sage", pt: "pelo excelente sábio", es: "por el excelente sabio" }, grammar: "noun (inst. sing.)" },
  { pali: "mohamūlāni", meaning: { en: "rooted in delusion", pt: "enraizado na ilusão", es: "enraizado en la ilusión" }, grammar: "adjective (pl.)" },
  { pali: "mayāpi", meaning: { en: "also by me", pt: "também por mim", es: "también por mí" }, grammar: "pronoun" },
  { pali: "matiyā", meaning: { en: "by wisdom; by intelligence", pt: "pela sabedoria; pela inteligência", es: "por la sabiduría; por la inteligencia" }, grammar: "noun (inst. sing.)" },
  { pali: "matipāṭavatthaṃ", meaning: { en: "for the purpose of skill in wisdom", pt: "com o propósito de habilidade na sabedoria", es: "con el propósito de habilidad en la sabiduría" }, grammar: "noun (acc. sing.)" },
  { pali: "matena", meaning: { en: "by what is known; by what is thought", pt: "pelo que é conhecido; pelo que é pensado", es: "por lo que se conoce; por lo que se piensa" }, grammar: "adjective (inst. sing.)" },
  { pali: "manussattabhāve", meaning: { en: "in the human existence", pt: "na existência humana", es: "en la existencia humana" }, grammar: "noun (loc. sing.)" },
  { pali: "manodvārāvajjanacittaṃ", meaning: { en: "mind-door adverting consciousness", pt: "consciência de advertência à porta da mente", es: "conciencia de advertencia a la puerta de la mente" }, grammar: "noun" },
  { pali: "manodvāraṃ", meaning: { en: "mind-door", pt: "porta da mente", es: "puerta de la mente" }, grammar: "noun" },
  { pali: "manodhātuṃ", meaning: { en: "mind-element", pt: "elemento da mente", es: "elemento de la mente" }, grammar: "noun" },
  { pali: "majjhe", meaning: { en: "in the middle", pt: "no meio", es: "en el medio" }, grammar: "noun (loc. sing.)" },
  { pali: "majjhattatā", meaning: { en: "neutrality; equanimity", pt: "neutralidade; equanimidade", es: "neutralidad; ecuanimidad" }, grammar: "noun" },
  { pali: "mahāni", meaning: { en: "great", pt: "grande", es: "gran" }, grammar: "adjective (pl.)" },
  { pali: "mahākiriyassa", meaning: { en: "of the great functional (consciousness)", pt: "da grande (consciência) funcional", es: "de la gran (conciencia) funcional" }, grammar: "noun (gen. sing.)" },
  { pali: "mahābhūtānaṃ", meaning: { en: "of the great elements", pt: "dos grandes elementos", es: "de los grandes elementos" }, grammar: "noun (gen. pl.)" },
  { pali: "mahābhūtā", meaning: { en: "great elements", pt: "grandes elementos", es: "grandes elementos" }, grammar: "noun (pl.)" },
  { pali: "mahaggatañceva", meaning: { en: "and exalted indeed", pt: "e exaltado de fato", es: "y exaltado de hecho" }, grammar: "adjective" },
  { pali: "mahaggatamānasā", meaning: { en: "exalted mind", pt: "mente exaltada", es: "mente exaltada" }, grammar: "noun" },
  { pali: "madhuādinā", meaning: { en: "by honey, etc.", pt: "por mel, etc.", es: "por miel, etc." }, grammar: "noun (inst. sing.)" },
  { pali: "lokuttare", meaning: { en: "in the supramundane", pt: "no supramundano", es: "en lo supramundano" }, grammar: "adjective (loc. sing.)" },
  { pali: "lokuttaracittesu", meaning: { en: "in the supramundane consciousnesses", pt: "nas consciências supramundanas", es: "en las conciencias supramundanas" }, grammar: "noun (loc. pl.)" }
];

fs.writeFileSync('/Users/pauloo/Desktop/abhidhamma/visuddhimagga/out2k_ae.json', JSON.stringify(data, null, 2));
