import json

data = [
    {"pali": "samasaṭṭhi", "meaning": {"en": "even sixty", "pt": "exatos sessenta", "es": "exactamente sesenta"}, "grammar": "adj."},
    {"pali": "sakadāgāmissa", "meaning": {"en": "for the once-returner", "pt": "para o que retorna uma vez", "es": "para el que retorna una vez"}, "grammar": "noun, genitive"},
    {"pali": "sahassaṃ", "meaning": {"en": "thousand", "pt": "mil", "es": "mil"}, "grammar": "noun"},
    {"pali": "sahagataṃ", "meaning": {"en": "accompanied by", "pt": "acompanhado por", "es": "acompañado por"}, "grammar": "adj."},
    {"pali": "sacittakā", "meaning": {"en": "with mind", "pt": "com mente", "es": "con mente"}, "grammar": "adj."},
    {"pali": "sabhāvena", "meaning": {"en": "by nature", "pt": "por natureza", "es": "por naturaleza"}, "grammar": "noun, instr."},
    {"pali": "sabhāvatikkheneva", "meaning": {"en": "by the very sharpness of its nature", "pt": "pela própria agudeza de sua natureza", "es": "por la agudeza misma de su naturaleza"}, "grammar": "noun, instr."},
    {"pali": "rūpāvacarā", "meaning": {"en": "of the fine-material sphere", "pt": "da esfera da matéria sutil", "es": "de la esfera de materia sutil"}, "grammar": "adj., plural"},
    {"pali": "rūpāvacarakusalaṃ", "meaning": {"en": "fine-material sphere wholesome", "pt": "benéfico da esfera da matéria sutil", "es": "beneficioso de la esfera de materia sutil"}, "grammar": "noun"},
    {"pali": "rūpārūpasamāpatti", "meaning": {"en": "fine-material and immaterial attainments", "pt": "realizações da matéria sutil e imaterial", "es": "logros de la materia sutil e inmaterial"}, "grammar": "noun"},
    {"pali": "rūpato", "meaning": {"en": "by way of form", "pt": "através da forma", "es": "por medio de la forma"}, "grammar": "noun, abl."},
    {"pali": "rūpanirodho", "meaning": {"en": "cessation of form", "pt": "cessação da forma", "es": "cesación de la forma"}, "grammar": "noun"},
    {"pali": "rūpaloke", "meaning": {"en": "in the fine-material world", "pt": "no mundo da matéria sutil", "es": "en el mundo de la materia sutil"}, "grammar": "noun, loc."},
    {"pali": "rūpakāyasampadā", "meaning": {"en": "perfection of the physical body", "pt": "perfeição do corpo físico", "es": "perfección del cuerpo físico"}, "grammar": "noun"},
    {"pali": "rūpabhave", "meaning": {"en": "in fine-material existence", "pt": "na existência da matéria sutil", "es": "en la existencia de la materia sutil"}, "grammar": "noun, loc."},
    {"pali": "rāgādayo", "meaning": {"en": "lust and so on", "pt": "luxúria e assim por diante", "es": "lujuria y así sucesivamente"}, "grammar": "noun, pl."},
    {"pali": "pūjito", "meaning": {"en": "honored", "pt": "honrado", "es": "honrado"}, "grammar": "pp."},
    {"pali": "pītisukhekaggatāsahitaṃ", "meaning": {"en": "accompanied by rapture, happiness, and one-pointedness", "pt": "acompanhado por êxtase, felicidade e unificação", "es": "acompañado de éxtasis, felicidad y unificación"}, "grammar": "adj."},
    {"pali": "pāṭho", "meaning": {"en": "reading / text", "pt": "leitura / texto", "es": "lectura / texto"}, "grammar": "noun"},
    {"pali": "pāpamānasaṃ", "meaning": {"en": "evil-minded", "pt": "mente perversa", "es": "mente malvada"}, "grammar": "adj."},
    {"pali": "pāpakānaṃ", "meaning": {"en": "of evil things", "pt": "das coisas ruins", "es": "de las cosas malas"}, "grammar": "adj., gen. pl."},
    {"pali": "pākacittāni", "meaning": {"en": "resultant consciousnesses", "pt": "consciências resultantes", "es": "consciencias resultantes"}, "grammar": "noun, pl."},
    {"pali": "puññārūpūparī", "meaning": {"en": "merit, immaterial, and above", "pt": "mérito, imaterial e acima", "es": "mérito, inmaterial y por encima"}, "grammar": "adj."},
    {"pali": "puññāpuññavipākā", "meaning": {"en": "wholesome and unwholesome results", "pt": "resultados benéficos e não benéficos", "es": "resultados beneficiosos y perjudiciales"}, "grammar": "noun, pl."},
    {"pali": "puññavipākakriyato", "meaning": {"en": "by way of wholesome, resultant, and functional", "pt": "através de benéfico, resultante e funcional", "es": "a través de beneficioso, resultante y funcional"}, "grammar": "noun, abl."},
    {"pali": "puññavasena", "meaning": {"en": "by way of merit", "pt": "por meio do mérito", "es": "por medio del mérito"}, "grammar": "noun, instr."},
    {"pali": "puññassa", "meaning": {"en": "of merit", "pt": "do mérito", "es": "del mérito"}, "grammar": "noun, gen."},
    {"pali": "puññakiriyāya", "meaning": {"en": "for the making of merit", "pt": "para a criação de mérito", "es": "para la creación de mérito"}, "grammar": "noun, dat."},
    {"pali": "puggalabhedo", "meaning": {"en": "distinction of individuals", "pt": "distinção de indivíduos", "es": "distinción de individuos"}, "grammar": "noun"},
    {"pali": "piṭake", "meaning": {"en": "in the basket", "pt": "na cesta", "es": "en la canasta"}, "grammar": "noun, loc."},
    {"pali": "phalacittena", "meaning": {"en": "by the fruit consciousness", "pt": "pela consciência do fruto", "es": "por la conciencia del fruto"}, "grammar": "noun, instr."},
    {"pali": "paṭṭhānanayo", "meaning": {"en": "method of conditional relations", "pt": "método das relações condicionais", "es": "método de relaciones condicionales"}, "grammar": "noun"},
    {"pali": "paṭisandhicittaṃ", "meaning": {"en": "rebirth-linking consciousness", "pt": "consciência de reconexão", "es": "conciencia de reconexión"}, "grammar": "noun"},
    {"pali": "paṭikkhipitabbā", "meaning": {"en": "should be rejected", "pt": "deve ser rejeitado", "es": "debe ser rechazado"}, "grammar": "grd., pl."},
    {"pali": "paṭiccasamuppādanayo", "meaning": {"en": "method of dependent origination", "pt": "método da originação dependente", "es": "método de la originación dependiente"}, "grammar": "noun"},
    {"pali": "paṭhamena", "meaning": {"en": "by the first", "pt": "pelo primeiro", "es": "por el primero"}, "grammar": "adj., instr."},
    {"pali": "paṭhamamahāsaṅgītikathā", "meaning": {"en": "account of the first great council", "pt": "relato do primeiro grande concílio", "es": "relato del primer gran concilio"}, "grammar": "noun"},
    {"pali": "paññattārammaṇattā", "meaning": {"en": "due to having a concept as object", "pt": "por ter um conceito como objeto", "es": "por tener un concepto como objeto"}, "grammar": "noun, abl."},
    {"pali": "pañcaṅgikaṃ", "meaning": {"en": "five-factored", "pt": "de cinco fatores", "es": "de cinco factores"}, "grammar": "adj."},
    {"pali": "pañcamena", "meaning": {"en": "by the fifth", "pt": "pelo quinto", "es": "por el quinto"}, "grammar": "adj., instr."},
    {"pali": "payogo", "meaning": {"en": "means / application / endeavor", "pt": "meio / aplicação / esforço", "es": "medio / aplicación / esfuerzo"}, "grammar": "noun"},
    {"pali": "pavuccate", "meaning": {"en": "is called / is spoken of", "pt": "é chamado / é falado de", "es": "es llamado / se habla de"}, "grammar": "verb"},
    {"pali": "pavattitvā", "meaning": {"en": "having proceeded / having occurred", "pt": "tendo ocorrido / tendo procedido", "es": "habiendo ocurrido / habiendo procedido"}, "grammar": "ger."},
    {"pali": "pavattite", "meaning": {"en": "in what has occurred", "pt": "no que ocorreu", "es": "en lo que ha ocurrido"}, "grammar": "pp., loc."},
    {"pali": "pavattattā", "meaning": {"en": "due to occurrence", "pt": "devido à ocorrência", "es": "debido a la ocurrencia"}, "grammar": "noun, abl."},
    {"pali": "parā", "meaning": {"en": "others / further", "pt": "outros / além", "es": "otros / más allá"}, "grammar": "adj."},
    {"pali": "pariyāyena", "meaning": {"en": "by a method / figuratively", "pt": "por um método / figurativamente", "es": "por un método / figurativamente"}, "grammar": "noun, instr."},
    {"pali": "parittārammaṇattā", "meaning": {"en": "due to having a limited object", "pt": "por ter um objeto limitado", "es": "por tener un objeto limitado"}, "grammar": "noun, abl."},
    {"pali": "pare", "meaning": {"en": "others", "pt": "outros", "es": "otros"}, "grammar": "adj., pl."},
    {"pali": "panete", "meaning": {"en": "but these", "pt": "mas estes", "es": "pero estos"}, "grammar": "pron."},
    {"pali": "panetassa", "meaning": {"en": "but of this", "pt": "mas deste", "es": "pero de este"}, "grammar": "pron., gen."},
    {"pali": "panekasmiṃ", "meaning": {"en": "but in one", "pt": "mas em um", "es": "pero en uno"}, "grammar": "pron., loc."},
    {"pali": "panatthe", "meaning": {"en": "but in the meaning", "pt": "mas no significado", "es": "pero en el significado"}, "grammar": "noun, loc."},
    {"pali": "pakāsitaṃ", "meaning": {"en": "explained / made known", "pt": "explicado / tornado conhecido", "es": "explicado / dado a conocer"}, "grammar": "pp."},
    {"pali": "pahānasampadā", "meaning": {"en": "success in abandoning", "pt": "sucesso no abandono", "es": "éxito en el abandono"}, "grammar": "noun"},
    {"pali": "nīvaraṇā", "meaning": {"en": "hindrances", "pt": "obstáculos", "es": "obstáculos"}, "grammar": "noun, pl."},
    {"pali": "nāpi", "meaning": {"en": "and not", "pt": "e não", "es": "y no"}, "grammar": "indec."},
    {"pali": "nāpajjati", "meaning": {"en": "does not come to", "pt": "não chega a", "es": "no llega a"}, "grammar": "verb"},
    {"pali": "nānākaraṇaṃ", "meaning": {"en": "difference / distinction", "pt": "diferença / distinção", "es": "diferencia / distinción"}, "grammar": "noun"},
    {"pali": "nānattaṃ", "meaning": {"en": "diversity", "pt": "diversidade", "es": "diversidad"}, "grammar": "noun"},
    {"pali": "nuppajjanti", "meaning": {"en": "do not arise", "pt": "não surgem", "es": "no surgen"}, "grammar": "verb, pl."},
    {"pali": "nisīditvā", "meaning": {"en": "having sat down", "pt": "tendo se sentado", "es": "habiéndose sentado"}, "grammar": "ger."},
    {"pali": "nipphādeti", "meaning": {"en": "accomplishes / produces", "pt": "realiza / produz", "es": "realiza / produce"}, "grammar": "verb"},
    {"pali": "nidānakathā", "meaning": {"en": "introductory talk", "pt": "conversa introdutória", "es": "charla introductoria"}, "grammar": "noun"},
    {"pali": "niddiṭṭho", "meaning": {"en": "pointed out / described", "pt": "apontado / descrito", "es": "señalado / descrito"}, "grammar": "pp."},
    {"pali": "niccaṃ", "meaning": {"en": "permanent / always", "pt": "permanente / sempre", "es": "permanente / siempre"}, "grammar": "adj. / adv."},
    {"pali": "nibbānañca", "meaning": {"en": "and Nibbāna", "pt": "e Nibbāna", "es": "y Nibbāna"}, "grammar": "noun"},
    {"pali": "nerayikānaṃ", "meaning": {"en": "of the hell-beings", "pt": "dos seres do inferno", "es": "de los seres del infierno"}, "grammar": "noun, gen. pl."},
    {"pali": "navakaṃ", "meaning": {"en": "group of nine / ninefold", "pt": "grupo de nove / nônuplo", "es": "grupo de nueve / nónuple"}, "grammar": "noun"},
    {"pali": "natthīti", "meaning": {"en": "'there is not'", "pt": "'não há'", "es": "'no hay'"}, "grammar": "verb + part."},
    {"pali": "naro", "meaning": {"en": "man / person", "pt": "homem / pessoa", "es": "hombre / persona"}, "grammar": "noun"},
    {"pali": "mūlabhavaṅganti", "meaning": {"en": "'the root life-continuum'", "pt": "'a raiz do contínuo vital'", "es": "'la raíz del continuo vital'"}, "grammar": "noun"},
    {"pali": "muñcanā", "meaning": {"en": "releasing", "pt": "libertação", "es": "liberación"}, "grammar": "noun"},
    {"pali": "muyhanti", "meaning": {"en": "are deluded / are confused", "pt": "estão iludidos / estão confusos", "es": "están engañados / están confundidos"}, "grammar": "verb, pl."},
    {"pali": "mukhanimittaṃ", "meaning": {"en": "sign of the mouth", "pt": "sinal da boca", "es": "signo de la boca"}, "grammar": "noun"},
    {"pali": "micchādiṭṭhiṃ", "meaning": {"en": "wrong view", "pt": "visão errônea", "es": "visión errónea"}, "grammar": "noun, acc."},
    {"pali": "micchādiṭṭhi", "meaning": {"en": "wrong view", "pt": "visão errônea", "es": "visión errónea"}, "grammar": "noun"},
    {"pali": "matthake", "meaning": {"en": "on the top / in the end", "pt": "no topo / no fim", "es": "en la cima / al final"}, "grammar": "noun, loc."},
    {"pali": "maraṇakāle", "meaning": {"en": "at the time of death", "pt": "no momento da morte", "es": "en el momento de la muerte"}, "grammar": "noun, loc."},
    {"pali": "manoviññāṇadhātuyā", "meaning": {"en": "of the mind-consciousness element", "pt": "do elemento da consciência mental", "es": "del elemento de la conciencia mental"}, "grammar": "noun, gen. / instr."},
    {"pali": "manodhātuttikaṃ", "meaning": {"en": "triad of the mind-element", "pt": "tríade do elemento da mente", "es": "tríada del elemento de la mente"}, "grammar": "noun"},
    {"pali": "manodhātuttayaṃ", "meaning": {"en": "triad of the mind-element", "pt": "tríade do elemento da mente", "es": "tríada del elemento de la mente"}, "grammar": "noun"},
    {"pali": "mandena", "meaning": {"en": "by the dull / slow", "pt": "pelo lento / obtuso", "es": "por el lento / torpe"}, "grammar": "adj., instr."},
    {"pali": "mahākriyāni", "meaning": {"en": "great functional (consciousnesses)", "pt": "grandes (consciências) funcionais", "es": "grandes (consciencias) funcionales"}, "grammar": "adj., pl."},
    {"pali": "mahaggatagocaraṃ", "meaning": {"en": "having a sublime object", "pt": "tendo um objeto sublime", "es": "teniendo un objeto sublime"}, "grammar": "adj."},
    {"pali": "lātabbattā", "meaning": {"en": "due to having to be taken", "pt": "por ter que ser pego", "es": "por tener que ser tomado"}, "grammar": "grd., abl."},
    {"pali": "lokuttarañceti", "meaning": {"en": "and supramundane", "pt": "e supramundano", "es": "y supramundano"}, "grammar": "adj. + part."},
    {"pali": "lokuttaraphalāni", "meaning": {"en": "supramundane fruits", "pt": "frutos supramundanos", "es": "frutos supramundanos"}, "grammar": "noun, pl."},
    {"pali": "lokuttaracittāni", "meaning": {"en": "supramundane consciousnesses", "pt": "consciências supramundanas", "es": "consciencias supramundanas"}, "grammar": "noun, pl."},
    {"pali": "lobhamūlāni", "meaning": {"en": "rooted in greed", "pt": "enraizados na cobiça", "es": "enraizados en la codicia"}, "grammar": "adj., pl."},
    {"pali": "lobhamūlaṃ", "meaning": {"en": "rooted in greed", "pt": "enraizado na cobiça", "es": "enraizado en la codicia"}, "grammar": "adj."},
    {"pali": "labhanti", "meaning": {"en": "obtain / get", "pt": "obtêm / conseguem", "es": "obtienen / consiguen"}, "grammar": "verb, pl."},
    {"pali": "kāmāvacarapuññassa", "meaning": {"en": "of the sense-sphere merit", "pt": "do mérito da esfera dos sentidos", "es": "del mérito de la esfera de los sentidos"}, "grammar": "noun, gen."},
    {"pali": "kāmāvacarakusalaṃ", "meaning": {"en": "sense-sphere wholesome", "pt": "benéfico da esfera dos sentidos", "es": "beneficioso de la esfera de los sentidos"}, "grammar": "noun"},
    {"pali": "kāmāvacaracittāni", "meaning": {"en": "sense-sphere consciousnesses", "pt": "consciências da esfera dos sentidos", "es": "consciencias de la esfera de los sentidos"}, "grammar": "noun, pl."},
    {"pali": "kāmā", "meaning": {"en": "sensual desires", "pt": "desejos sensuais", "es": "deseos sensuales"}, "grammar": "noun, pl."},
    {"pali": "kāmeyeva", "meaning": {"en": "only in sensual desires", "pt": "apenas nos desejos sensuais", "es": "solo en los deseos sensuales"}, "grammar": "noun, loc. + part."},
    {"pali": "kāmato", "meaning": {"en": "from sensual desire", "pt": "do desejo sensual", "es": "del deseo sensual"}, "grammar": "noun, abl."},
    {"pali": "kāmapākaṃ", "meaning": {"en": "sense-sphere resultant", "pt": "resultante da esfera dos sentidos", "es": "resultante de la esfera de los sentidos"}, "grammar": "noun"},
    {"pali": "kāmalokasmiṃ", "meaning": {"en": "in the sense-sphere world", "pt": "no mundo da esfera dos sentidos", "es": "en el mundo de la esfera de los sentidos"}, "grammar": "noun, loc."}
]

with open("/Users/pauloo/Desktop/abhidhamma/visuddhimagga/out1k_ai.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
